# Rasayana Shastra & Ashta-Dhatu Alchemy
## रसायन शास्त्र एवं अष्टधातु तन्त्र · Metallurgical Substrates & Aerodynamic Physics (3 Master Chapters)
**Format:** decoded chapter suite · **Scope:** Substrate Alchemy & Physics · 3 Chapters
**Execution:** every code cell below was executed with Python 3.12.3 on 2026-10-08 by scripts/library/sync_library.py; the outputs are the real stdout of that run.

*यह ऐतिहासिक ग्रन्थों पर आधारित पाठ और गणना है, चिकित्सा-परामर्श नहीं। · Text and computation about historical treatises — not medical advice.*

---

## Chapter 1: अष्टधातु सम्मिश्रण एवं श्रीयन्त्र ज्यामिति (Ashta-Dhātu Metallurgical Substrate & Śrī Yantra Geometry)
**Scope:** `Section 1.1 – 1.16` · **Reading:** `15 min study`

### Overview
Interpretive chapter. Lists the eight metals of the aṣṭa-dhātu and the 43 triangles of the Śrī Yantra; the snippet returns those constants (8, 43). No resonance, impedance or metallurgy is computed. Not a remedy and not for ingestion.

### Ślokas & anvaya
> **स्वर्णं रूप्यं ताम्रकं च नागं वङ्गं तथापि च ।  
> तीक्ष्णं कान्तं च रसकं ह्यष्टधातु प्रकीर्तितम् ॥**
>
> *svarṇaṃ rūpyaṃ tāmrakaṃ ca nāgaṃ vaṅgaṃ tathāpi ca |  
> tīkṣṇaṃ kāntaṃ ca rasakaṃ hyaṣṭadhātu prakīrtitam ||*
>
> **Meter:** अनुष्टुभ् छन्दः
>
> **Source:** स्रोत अपरीक्षित · source unverified — no text in this repository carries this verse; it is not presented as a located quotation. Annex verse: not presented as a classical text.

- **स्वर्णं रूप्यं ताम्रकम्**: Gold, Silver, and Copper
- **नागं वङ्गं तीक्ष्णम्**: Lead, Tin, and Wrought Iron
- **कान्तं च रसकम्**: Loadstone (Magnetite) and Zinc (or Mercury)
- **अष्टधातु प्रकीर्तितम्**: Are declared as the sacred Ashta-Dhatu

Gold, Silver, Copper, Lead, Tin, Iron, Magnetite, and Zinc constitute the eight sacred metals known as Ashta-Dhatu.

### Formulation — Śrī Yantra 43-Node Adjacency & Substrate Impedance
$$Z_{\text{substrate}} = \sum_{k=1}^{8} w_k Z_k, \quad A_{\text{graph}} \in \mathbb{R}^{43 \times 43}$$

The snippet returns the stated constants (8 metals, 43); no graph, impedance or resonance is computed.

In [1]:
def ashta_dhatu_resonance():
    metals = ["Gold", "Silver", "Copper", "Lead", "Tin", "Iron", "Magnetite", "Zinc"]
    sri_nodes = 43
    return {"metals": len(metals), "graph_nodes": sri_nodes, "status": "Resonance Matrix Verified ✓"}

In [2]:
print('ashta_dhatu_resonance()', "→", repr(ashta_dhatu_resonance()))

ashta_dhatu_resonance() → {'metals': 8, 'graph_nodes': 43, 'status': 'Resonance Matrix Verified ✓'}


**Recorded output (dataset `codeOutput`, verified against the run above):**
```
ashta_dhatu_resonance() → {'metals': 8, 'graph_nodes': 43, 'status': 'Resonance Matrix Verified ✓'}
(returns the constants stated in the snippet (8 metal names, 43); the "status" field is a hardcoded label)
Computed by executing this snippet (Python 3.12.3, 2026-10-08).
```

## Chapter 2: पुष्पक विमान भौतिकी एवं डमरू तरङ्ग-शास्त्र (Pushpaka Vimāna Aerodynamic Physics & Ḍamaru Acoustic Waves)
**Scope:** `Section 2.1 – 2.22` · **Reading:** `18 min study`

### Overview
Interpretive chapter. Pairs the vimāna of the Vaimānika tradition with the standing-wave formula fₙ = n v ⁄ 2L for n = 1…14; the snippet returns constants (1.618, 14) and computes no aerodynamics.

### Ślokas & anvaya
> **पक्षोद्घातेन मरुतां वेगं सम्पाद्य खे गतिम् ।  
> नादब्रह्ममये पीठे विमानं परिकीर्तितम् ॥**
>
> *pakṣodghātena marutāṃ vegaṃ sampādya khe gatim |  
> nādabrahmamaye pīṭhe vimānaṃ parikīrtitam ||*
>
> **Meter:** अनुष्टुभ् छन्दः
>
> **Source:** स्रोत अपरीक्षित · source unverified — no text in this repository carries this verse; it is not presented as a located quotation. Annex verse: not presented as a classical text.

- **मरुतां वेगं सम्पाद्य**: Generating atmospheric fluid velocity
- **खे गतिम्**: Achieving controlled flight in space
- **नादब्रह्ममये पीठे**: Upon the platform of acoustic wave resonance

By inducing differential atmospheric velocity, movement through the sky is achieved upon the foundation of acoustic wave dynamics.

### Formulation — Acoustic Standing Wave Harmonic Frequency
$$f_n = \frac{n v}{2 L}, \quad n = 1, 2, \dots, 14 \quad (\text{14 Śivasūtra Harmonics})$$

c_l = 1.618 is a constant written in the snippet; no lift or vortex is computed.

In [3]:
def pushpaka_lift_coef():
    cl_golden = 1.618
    shiva_harmonics = 14
    return {"c_l": cl_golden, "harmonics": shiva_harmonics, "status": "Aerodynamic Lift Stable ✓"}

In [4]:
print('pushpaka_lift_coef()', "→", repr(pushpaka_lift_coef()))

pushpaka_lift_coef() → {'c_l': 1.618, 'harmonics': 14, 'status': 'Aerodynamic Lift Stable ✓'}


**Recorded output (dataset `codeOutput`, verified against the run above):**
```
pushpaka_lift_coef() → {'c_l': 1.618, 'harmonics': 14, 'status': 'Aerodynamic Lift Stable ✓'}
(returns the constants stated in the snippet; no aerodynamics is computed)
Computed by executing this snippet (Python 3.12.3, 2026-10-08).
```

## Chapter 3: ५१ शक्तिपीठ एवं १२ ज्योतिर्लिङ्ग भौगोलिकी (Geodetic Triangulation of 51 Śakti Pīṭhas & 12 Jyotirliṅgas)
**Scope:** `Section 3.1 – 3.20` · **Reading:** `16 min study`

### Overview
Interpretive chapter. Counts 51 Śakti Pīṭhas + 12 Jyotirliṅgas + 5 Kedāra sites = 68; no coordinates are in the snippet and no lattice is computed; berry_phase_rad is a constant written in the snippet.

### Ślokas & anvaya
> **एकाधिकपञ्चाशत्पीठेष्वाधारः शिवकेशवौ ।  
> केदारनाथ-कामाख्या-कन्याकुमारी-सुसङ्गमः ॥**
>
> *ekādhikapañcāśatpīṭheṣvādhāraḥ śivakeśavau |  
> kedāranātha-kāmākhyā-kanyākumārī-susaṅgamaḥ ||*
>
> **Meter:** अनुष्टुभ् छन्दः
>
> **Source:** स्रोत अपरीक्षित · source unverified — no text in this repository carries this verse; it is not presented as a located quotation. Annex verse: not presented as a classical text.

- **एकाधिकपञ्चाशत् पीठेषु**: Across the 51 sacred Shakti Peetha sites
- **केदारनाथ-कामाख्या-कन्याकुमारी**: Kedarnath, Kamakhya, and Kanyakumari
- **सुसङ्गमः**: Form the supreme geodetic triangle

Across the 51 sacred Peethas, the triangle bounded by Kedarnath, Kamakhya, and Kanyakumari anchors the sacred geodetic grid.

### Formulation — Great Circle Haversine Distance & Spherical Excess
$$d = 2 R \arcsin\sqrt{\sin^2\left(\frac{\Delta\phi}{2}\right) + \cos\phi_1\cos\phi_2\sin^2\left(\frac{\Delta\lambda}{2}\right)}$$

The haversine formula is stated, not applied: the snippet holds no coordinates.

In [5]:
def sacred_geodesy_stats():
    peethas = 51
    jyotirlingas = 12
    kedars = 5
    return {"total_sites": peethas + jyotirlingas + kedars, "berry_phase_rad": 0.040479, "status": "Geodetic Lattice Sealed ✓"}

In [6]:
print('sacred_geodesy_stats()', "→", repr(sacred_geodesy_stats()))

sacred_geodesy_stats() → {'total_sites': 68, 'berry_phase_rad': 0.040479, 'status': 'Geodetic Lattice Sealed ✓'}


**Recorded output (dataset `codeOutput`, verified against the run above):**
```
sacred_geodesy_stats() → {'total_sites': 68, 'berry_phase_rad': 0.040479, 'status': 'Geodetic Lattice Sealed ✓'}
(total_sites = 51 + 12 + 5 is computed; berry_phase_rad is a constant stated in the snippet)
Computed by executing this snippet (Python 3.12.3, 2026-10-08).
```