/* gurutva-candra.js — GENERATED by scripts/derive-gurutva.cjs from corpus/gurutva/candra.json; do not edit by hand.
 * The text's mean Moon (Sūrya-Siddhānta) with the periodic terms that Newton's law adds when it is given only the text's
 * numbers: the equation of centre and its harmonics, evection, variation, the annual equation, the reduction to the
 * ecliptic, and the latitude terms. The arguments are the text's own mean elements. The Sun stays the text's Sun.
 * placesAt(t) has the shape of Sphuta.sphutaAtDays(t), so Panchanga.withPlaces(GurutvaCandra.placesAt) uses it.
 * Browser: window.GurutvaCandra (needs Sphuta); node: module.exports.
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory(require("./sphuta.js").withSine("table"));
  else root.GurutvaCandra = factory(root.Sphuta.withSine("table"));
})(typeof globalThis !== "undefined" ? globalThis : this, function (S) {
  "use strict";
  const D2R = Math.PI / 180, mod = (a, m) => ((a % m) + m) % m;
  const LON = Object.freeze([[0,1,0,0,6.338907,0],[0,2,0,0,0.217084,0.000007],[0,3,0,0,0.010278,-0.000001],[2,-1,0,0,1.28491,0.000002],[2,0,0,0,0.661056,0.000003],[2,-2,0,0,0.059789,-0.000007],[2,1,0,0,0.05397,-0.000005],[2,-3,0,0,0.003734,-0.000003],[0,0,1,0,-0.211435,0.000004],[2,0,-1,0,0.052343,-0.000001],[2,-1,-1,0,0.065621,-0.000003],[2,0,1,0,-0.007788,-0.000013],[0,1,-1,0,0.047132,-0.000005],[0,1,1,0,-0.035009,-0.000002],[2,-1,1,0,-0.009043,-0.000001],[1,0,0,0,0.000001,0.000032],[1,1,0,0,-0.000034,0.000105],[1,0,1,0,0.000029,-0.00003],[0,0,0,2,-0.094273,-0.000018],[2,0,0,-2,0.012635,0.000004],[0,1,0,-2,0.009044,-0.00007],[0,1,0,2,-0.010411,-0.000001],[4,-1,0,0,0.01082,0],[4,-2,0,0,0.008671,-0.000011],[4,0,0,0,0.003909,0.000002],[0,0,2,0,-0.00269,-0.000004],[2,-2,-1,0,0.002775,-0.000006],[2,1,-1,0,0.004659,0.000003]]);
  const LAT = Object.freeze([[0,0,0,1,4.657297,0],[0,1,0,1,0.256864,-0.000002],[0,1,0,-1,0.254039,-0.000008],[2,0,0,-1,0.157256,0.000003],[2,-1,0,1,0.050784,0.000007],[2,-1,0,-1,0.042394,0],[2,0,0,1,0.029724,0.000001],[0,2,0,1,0.015864,0],[0,2,0,-1,0.008109,0.000008],[2,1,0,-1,0.008481,-0.000021],[2,-2,0,-1,0.003997,0.000003],[2,0,-1,-1,0.008504,0.000003],[0,0,1,1,-0.001867,-0.000002],[0,0,1,-1,-0.001402,-0.000004],[0,0,0,3,-0.001307,-0.000004],[2,-2,0,1,-0.000407,-0.000019]]);
  const RATES = Object.freeze({"span_years":74.4,"moonPerYuga":57753327.7,"apogeePerYuga":489246,"nodePerYuga":232449.3,"text":{"moon":57753336,"apogee":488203,"node":232238},"apogeeRatio":1.0021364,"nodeRatio":1.00091});
  function sum(list, a) { let s = 0; for (const r of list) { const x = (r[0] * a[0] + r[1] * a[1] + r[2] * a[2] + r[3] * a[3]) * D2R; s += r[4] * Math.sin(x) + r[5] * Math.cos(x); } return s; }
  /** Places at t (civil days since the Kali epoch): the text's Sun and node; the Moon by the text's mean and gravitation's terms. */
  function placesAt(t) {
    const base = S.sphutaAtDays(t), m = base.mean;
    const a = [m.moon - m.sun, m.moon - m.moonApogee - 180, m.sun - m.sunApogee - 180, m.moon - m.node];
    const dl = sum(LON, a);
    return { ...base, moon: mod(m.moon + dl, 360), moonLatitude: sum(LAT, a), equations: { ...base.equations, moon: { degrees: dl, model: "gurutva" } }, model: "gurutva" };
  }
  return Object.freeze({ LON, LAT, RATES, placesAt });
});
