/* siddhanta-tier.js — the "Modern Bhāratīya (dṛk)" tier · आधुनिक भारतीय (दृक्) · 2026-10-08
 *
 * The one gate to the owner's dṛk-siddhānta series (siddhanta-drik.js, generated by bharat-sovereign-engine
 * scripts/build-browser-siddhanta.cjs from data/drik-siddhanta-series.json, the production series v2.4.2 of that
 * engine's README/CHANGELOG). Nothing else in this repository may call SiddhantaDrik.*: outside its span the raw series
 * returns finite but wrong values (1849.99, 2150.01) or NaN (JD 0, ±2^23 d, ±50,000 y), so every entry here is guarded.
 *
 * WHAT IS OURS (the owner's derivations, used together as one chain):
 *   1. law: DOP853 with the owner's force model (Newton + EIH 1PN + Earth J2 + lunar figure + LLR tide), restarted from
 *      NASA-JPL DE440s states every 720 days (154 anchors, each integrated ±360 d);
 *   2. fit: 12,901 periodic terms (+157 slow terms) fitted to every daily sample 1800.12–2199.91 of that N-body,
 *      evaluated in the Sūrya-Siddhānta's order (madhyama, manda, śīghra) with Mādhava's sine for the periodic terms
 *      (the 29 long-period corrections of the mean longitudes and the Earth-orientation rotations use Math.sin/cos);
 *   3. reduction: planets heliocentric − E with two light-time iterations, the Sun's deflection and relativistic
 *      annual aberration; the Sun −E with aberration; the Moon geocentric, retarded by its own light-time;
 *   4. Earth orientation (EO, embedded in siddhanta-drik.js; code identical to the engine's earth-orientation.cjs):
 *      IAU 2006 precession (Fukushima–Williams), IAU 2000B nutation (77 terms), ERA/GMST/GAST — our implementation of
 *      the IAU models;
 *   5. ayanāṃśa: Citrā-pakṣa (Lahiri), ported from bharat-sovereign-engine src/chart/chart.cjs:53-75 (the IAE value
 *      23°15′00.658″ for 1956-03-21 = JD 2435553.5, true equinox; referred to the mean equinox by Swiss's Δψ(t0) =
 *      0.004660222°; + the 0.138235″ by which Swiss Ephemeris realises SE_SIDM_LAHIRI; carried by IAU 2006 p_A).
 *      Applied TRUE: sidereal λ = apparent λ − (mean + Δψ) = the series' mean-equinox longitude − mean; the displayed
 *      ayanāṃśa is the applied one (deg = mean + Δψ);
 *   6. lagna / madhya-lagna: chart.cjs:83-91 ascMc (apparent sidereal time = ERA + IAU 2006 GMST + equation of the
 *      equinoxes; true obliquity), minus the true ayanāṃśa;
 *   7. sunrise/sunset: the Sun's upper limb on the horizon with 34′ refraction (the centre at −50′) [convention];
 *      moonrise/moonset: the Moon's centre on a net +7′ geocentric horizon (parallax − refraction − semi-diameter;
 *      owner decision DK-5, KH-13 unchanged) [convention]; both with IAU 2006 GAST from the EO;
 *   8. eclipses: drik-grahana.js, a search on this tier's own Sun and Moon (owner decision DK-3).
 * EXTERNAL INPUTS (not ours): the DE440s states (through the fit), DE440 GM values and constants, the IAU 2006/2000B
 *   models, the ΔT data (math-core observedDeltaTSeconds: annual table 1800–2027, Espenak–Meeus prediction after),
 *   the IAE ayanāṃśa constant and Swiss's +0.138″ realisation offset.
 * SPAN: 1850.0 ≤ y ≤ 2150.0 with y = 2000 + (jdTT − 2451545)/365.25 (the series' own rule, siddhanta-drik.js core
 *   inCertifiedSpan). Outside it every entry returns null (DK-1 = refuse; no foreign fallback). A block that needs any
 *   instant outside the span (a month or year straddling an edge) is refused the same way (EDGE RULE).
 * INPUTS: a Julian day, a latitude or a longitude that is not a finite number throws TypeError (a bad argument is never
 *   reported as an out-of-span refusal, which stays null); a latitude at or beyond ±90° or a longitude beyond ±360°
 *   throws RangeError. AYANĀṂŚA: the tier has one, Citrā-pakṣa (true). Every entry that takes options throws RangeError
 *   on any other named ayanāṃśa (opts.ayanamsha, or a string in the options' place); the entries without options say so
 *   in their doc and refuse a named ayanāṃśa passed in an extra argument the same way.
 * HONESTY: agreement with DE440s (λ ≤ 0.9″, dense) is not independence from JPL — the N-body is restarted from DE440s
 *   states. ΔT after 2027 is a prediction, so civil (UT) times after 2027 carry its uncertainty. Rāhu is the mean node.
 * The vendored VSOP87B + ELP/MPP02 and Astronomy Engine are never called from here: they stay referees in the tests.
 * Works in the browser (window.SiddhantaTier; needs siddhanta-drik.js and math-core.js loaded first) and in node.
 */
(function (root) {
  "use strict";
  const J2000 = 2451545.0, DEG = Math.PI / 180, C_AUDAY = 173.1446326847695;
  const SPAN_YEARS = Object.freeze([1850, 2150]);
  const n360 = (x) => ((x % 360) + 360) % 360;
  const wrap180 = (x) => { const y = n360(x); return y > 180 ? y - 360 : y; };

  // ── loading ───────────────────────────────────────────────────────────────────────────────────────────────────────
  function getSD() {
    if (root.SiddhantaDrik) return root.SiddhantaDrik;
    if (typeof require === "function") { try { return require("./siddhanta-drik.js"); } catch (e) { /* not present */ } }
    return null;
  }
  function getMath() {
    if (root.ShunyaMath) return root.ShunyaMath;
    if (typeof require === "function") { try { return require("./math-core.js"); } catch (e) { /* not present */ } }
    return null;
  }
  function getPanchanga() {
    if (root.Panchanga) return root.Panchanga;
    if (typeof require === "function") { try { return require("./panchanga.js"); } catch (e) { /* not present */ } }
    return null;
  }

  /** ΔT = TT − UT1 in seconds at a UT Julian day: math-core observedDeltaTSeconds (annual table 1800–2027, then the
   *  Espenak–Meeus prediction joined continuously). No silent substitute: without math-core this throws. No options. */
  function deltaTSeconds(jdUT) {
    requireFinite(jdUT, "deltaTSeconds", "the Julian day (UT)");
    const M = getMath();
    if (!M || typeof M.observedDeltaTSeconds !== "function") throw new Error("siddhanta-tier.js: ΔT needs math-core.js (observedDeltaTSeconds) loaded first");
    return M.observedDeltaTSeconds(jdUT - J2000);
  }
  /** A finite number, or TypeError naming the entry and the argument (never null: null means "outside the span"). */
  function requireFinite(x, entry, what) {
    if (typeof x !== "number" || !Number.isFinite(x)) throw new TypeError(`SiddhantaTier.${entry}: ${what} must be a finite number (got ${typeof x === "number" ? x : typeof x})`);
    return x;
  }
  const yearOfTT = (jdTT) => 2000 + (jdTT - J2000) / 365.25;
  /** Is the TT instant in the span? A non-finite argument throws TypeError. No options. */
  function inSpanTT(jdTT) {
    requireFinite(jdTT, "inSpanTT", "the Julian day (TT)");
    const y = yearOfTT(jdTT);
    return y >= SPAN_YEARS[0] && y <= SPAN_YEARS[1];
  }
  /** jd (UT unless opts.timeScale === 'TT') → jdTT, or null when outside the span; TypeError when not a finite number. */
  function ttOf(jd, opts, entry = "entry") {
    requireFinite(jd, entry, "the Julian day");
    const jdTT = (opts && opts.timeScale === "TT") ? jd : jd + deltaTSeconds(jd) / 86400;
    return inSpanTT(jdTT) ? jdTT : null;
  }
  /** Is jd (UT; opts.timeScale 'TT' for TT) in the span? opts: { timeScale, ayanamsha: 'citra-paksha' only }. */
  function inSpan(jd, opts) { rejectNamedAyanamsha(opts); return ttOf(jd, opts, "inSpan") !== null; }
  /** The UT instant of a TT instant (fixed point; ΔT varies by < 1e-4 s over the iteration). No options. */
  function utOfTT(jdTT) {
    requireFinite(jdTT, "utOfTT", "the Julian day (TT)");
    let u = jdTT;
    for (let k = 0; k < 4; k++) u = jdTT - deltaTSeconds(u) / 86400;
    return u;
  }
  let SPAN_JD_UT = null;
  /** The span in UT Julian days: [first, last] instant served (y = 1850.0 and 2150.0 in TT). No options. */
  function spanJdUT() {
    if (!SPAN_JD_UT) SPAN_JD_UT = Object.freeze(SPAN_YEARS.map((y) => utOfTT(J2000 + (y - 2000) * 365.25)));
    return SPAN_JD_UT.slice();
  }

  // ── internal guard: a computation that needs an instant outside the span stops here (EDGE RULE) ─────────────────────
  const OUT = Object.freeze({ outOfSpan: true });
  function need(jdTT) { if (!inSpanTT(jdTT)) throw OUT; return jdTT; }
  function guarded(fn) {
    return function () {
      try { return fn.apply(null, arguments); } catch (e) { if (e === OUT) return null; throw e; }
    };
  }
  /** The tier's one ayanāṃśa: undefined, null, '' or 'citra-paksha' pass; any other name (a string, or opts.ayanamsha)
   *  throws RangeError. */
  function rejectNamedAyanamsha(x) {
    const name = typeof x === "string" ? x : (x && typeof x === "object" ? x.ayanamsha : undefined);
    if (name === undefined || name === null || name === "" || name === "citra-paksha") return;
    throw new RangeError(`SiddhantaTier: the dṛk tier's ayanāṃśa is Citrā-pakṣa (true) only (owner decision DK-2, 2026-10-08); "${name}" is not accepted here`);
  }
  const optsOf = (x) => (x && typeof x === "object") ? x : {};

  // ── Citrā-pakṣa ayanāṃśa (port of bharat-sovereign-engine src/chart/chart.cjs:53-75) ─────────────────────────────────
  const LAHIRI_T0_JD = 2435553.5;                     // 1956-03-21 0h TT (the IAE epoch)
  const LAHIRI_IAE_TRUE_DEG = 23.250182778;           // 23°15′00.658″, true equinox
  const DPSI_T0_SWISS_DEG = 0.004660222;              // Δψ(t0) as Swiss Ephemeris uses it (own IAU 2000B: 0.004660198°)
  const SWISS_REALISATION_ARCSEC = 0.138235;          // Swiss realises SE_SIDM_LAHIRI 0.138235″ above the nominal constant
  const LAHIRI_T0_MEAN_DEG = LAHIRI_IAE_TRUE_DEG - DPSI_T0_SWISS_DEG + SWISS_REALISATION_ARCSEC / 3600;
  let PA_T0 = null;
  function ayanParts(jdTT) {
    const EO = getSD().EO, T = (jdTT - J2000) / 36525;
    if (PA_T0 === null) PA_T0 = EO.generalPrecessionArcsec((LAHIRI_T0_JD - J2000) / 36525);
    const mean = LAHIRI_T0_MEAN_DEG + (EO.generalPrecessionArcsec(T) - PA_T0) / 3600;
    const dpsi = EO.nutation(T).dpsi / 3600;
    return { mean, dpsi, true: mean + dpsi, T };
  }
  /** The applied ayanāṃśa at jd (UT; opts.timeScale 'TT'): { deg (true), meanDeg, nutationDeg, rate, … }. opts:
   *  { timeScale, ayanamsha: 'citra-paksha' only }. null outside the span. */
  const ayanamsha = guarded(function (jd, opts) {
    rejectNamedAyanamsha(opts); const o = optsOf(opts);
    if (!getSD()) return null;
    const jdTT = ttOf(jd, o, "ayanamsha"); if (jdTT === null) return null;
    const a = ayanParts(jdTT), EO = getSD().EO;
    const rate = (EO.generalPrecessionArcsec(a.T + 1e-3) - EO.generalPrecessionArcsec(a.T - 1e-3)) / 2e-3 / 100;   // ″/yr
    return {
      deg: a.true, trueDeg: a.true, meanDeg: a.mean, nutationDeg: a.dpsi, jd, jdTT,
      name: "citra-paksha", label: "Citrā-pakṣa (Lahiri), true", rateArcsecPerYear: rate, source: "own",
      t0: { jd: LAHIRI_T0_JD, trueDeg: LAHIRI_IAE_TRUE_DEG, swissArcsec: SWISS_REALISATION_ARCSEC, dpsiDeg: DPSI_T0_SWISS_DEG },
      rule: "IAE 23°15′00.658″ at JD 2435553.5 (true equinox) − Swiss Δψ(t0) + 0.138235″, moved by IAU 2006 p_A; + Δψ (true)",
    };
  });

  // ── the series' reduction, restricted to the Sun and the Moon (a copy of drik-siddhanta-core apparent() and the
  //    of-date branch of grahaOfDate(); a test keeps it bit-identical to SiddhantaDrik.grahaOfDate) ────────────────────
  const sub = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]], scl = (a, s) => [a[0] * s, a[1] * s, a[2] * s];
  const dot = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2], nrm = (a) => Math.hypot(a[0], a[1], a[2]), unit = (a) => scl(a, 1 / nrm(a));
  function seriesFrameOk(SD) { return SD.series.frame === "ecliptic-of-date-sidereal"; }
  function apparentSun(E, Ev) {
    const geo = scl(E, -1), dist = nrm(geo);
    const p = unit(geo);
    const V = scl(Ev, 1 / C_AUDAY), V2 = dot(V, V), binv = Math.sqrt(1 - V2), pV = dot(p, V);
    const f2 = 1 + pV / (1 + binv), num = [binv * p[0] + f2 * V[0], binv * p[1] + f2 * V[1], binv * p[2] + f2 * V[2]];
    return { u: unit(scl(num, 1 / (1 + pV))), dist };
  }
  function apparentMoon(vec, t) {
    let geo = vec("M", t); for (let k = 0; k < 2; k++) { const tau = nrm(geo) / C_AUDAY; geo = vec("M", t - tau); }
    return { u: unit(geo), dist: nrm(geo) };
  }
  const VELOCITY_STEP = 0.02;                         // the core's velocity(): central difference over ±0.02 d
  /** Apparent Sun (and Moon) in the series frame at jdTT from a vector source vec(body, t) (t = jdTT − J2000 days;
   *  body 'E' heliocentric Earth, 'M' geocentric Moon): the series itself, or an interpolant of it (drik-grahana.js).
   *  Returns { t, T, sun: {u, dist}, moon?: {u, dist} }. */
  function reduceSunMoonWith(vec, jdTT, withMoon) {
    const t = jdTT - J2000, T = (jdTT - J2000) / 36525, h = VELOCITY_STEP;
    const E = vec("E", t), Ev = scl(sub(vec("E", t + h), vec("E", t - h)), 1 / (2 * h));
    const out = { t, T, sun: apparentSun(E, Ev) };
    if (withMoon) out.moon = apparentMoon(vec, t);
    return out;
  }
  function seriesVec() { const SD = getSD(), S = SD.series, C = SD.core; C.prepare(S); return (b, t) => C.vector(S, b, t); }
  /** The same on the series itself, with the frame angles: { t, T, pA, dpsi, sun, moon? }. */
  function reduceSunMoon(jdTT, withMoon) {
    const EO = getSD().EO, out = reduceSunMoonWith(seriesVec(), jdTT, withMoon);
    out.dpsi = EO.nutation(out.T).dpsi / 3600; out.pA = EO.generalPrecessionArcsec(out.T) / 3600;
    return out;
  }
  const lonMeanOf = (u, pA) => n360(Math.atan2(u[1], u[0]) / DEG + pA);
  const latOf = (u) => Math.asin(Math.max(-1, Math.min(1, u[2]))) / DEG;

  /** True obliquity ε_A + Δε (radians) at TT centuries T. */
  function trueObliquityRad(T) { const EO = getSD().EO; return EO.meanObliquityRad(T) + EO.nutation(T).deps * EO.AS2R; }
  /** Series-frame unit vector → true equator & equinox of date: rotate by p_A + Δψ about the ecliptic pole of date,
   *  then by the true obliquity about the x-axis (N·R1(−ε_A) = R1(−(ε_A+Δε))·R3(−Δψ)). */
  function toTrueEquator(u, pAdeg, dpsiDeg, eps) {
    const th = (pAdeg + dpsiDeg) * DEG, c = Math.cos(th), s = Math.sin(th);
    const x = u[0] * c - u[1] * s, y = u[0] * s + u[1] * c, z = u[2];
    const ce = Math.cos(eps), se = Math.sin(eps);
    return [x, y * ce - z * se, y * se + z * ce];
  }
  function raDecOfLonLat(lonDeg, latDeg, eps) {
    const l = lonDeg * DEG, b = latDeg * DEG;
    const x = Math.cos(b) * Math.cos(l), y = Math.cos(b) * Math.sin(l) * Math.cos(eps) - Math.sin(b) * Math.sin(eps);
    const z = Math.cos(b) * Math.sin(l) * Math.sin(eps) + Math.sin(b) * Math.cos(eps);
    return { ra: n360(Math.atan2(y, x) / DEG), dec: Math.asin(Math.max(-1, Math.min(1, z))) / DEG };
  }

  // ── grahas ──────────────────────────────────────────────────────────────────────────────────────────────────────
  const ORDER = Object.freeze(["surya", "candra", "mangala", "budha", "guru", "shukra", "shani", "rahu", "ketu"]);
  const ENGINE = Object.freeze({ surya: "surya", candra: "chandra", mangala: "mangala", budha: "budha", guru: "guru", shukra: "shukra", shani: "shani", rahu: "rahu", ketu: "ketu" });
  const SERIES_BODY = Object.freeze({ mangala: "Ma", budha: "Me", guru: "Ju", shukra: "Ve", shani: "Sa" });
  const NAMES = Object.freeze({ surya: ["सूर्यः", "Sun"], candra: ["चन्द्रः", "Moon"], mangala: ["मङ्गलः", "Mars"], budha: ["बुधः", "Mercury"], guru: ["गुरुः", "Jupiter"], shukra: ["शुक्रः", "Venus"], shani: ["शनिः", "Saturn"], rahu: ["राहुः", "Rāhu"], ketu: ["केतुः", "Ketu"] });
  const SPEED_STEP_DAYS = 0.01;
  /** Speeds (deg/day) of the sidereal longitudes: the rate of the geometric geocentric direction in the series frame
   *  (whose longitude differs from the sidereal one by a constant), central difference ±0.01 d; Rāhu/Ketu the fitted
   *  node line's rate. Differs from the rate of the served (apparent) longitude by the light-time, aberration and
   *  deflection terms: measured ≤ 0.02″/day for the Sun and Moon, ≤ 3.3″/day for the planets at elongation ≥ 3° (Mercury,
   *  light-time), and up to 31″/day for Venus passing behind the Sun (the deflection formula); 2000 epochs 1850–2150. */
  function speedsTT(jdTT) {
    const SD = getSD(), S = SD.series, C = SD.core; C.prepare(S);
    const t = jdTT - J2000, h = SPEED_STEP_DAYS;
    // central difference inside the span; at an edge instant a one-sided 3-point stencil that stays inside (O(h²) both)
    const side = inSpanTT(jdTT - h) && inSpanTT(jdTT + h) ? 0 : (inSpanTT(jdTT + 2 * h) ? 1 : -1);
    const xs = side === 0 ? [t - h, t + h] : [t, t + side * h, t + side * 2 * h];
    for (const x of xs) need(x + J2000);
    const lon = (v) => Math.atan2(v[1], v[0]) / DEG;
    const rate = (vs) => {
      const L = vs.map(lon);
      if (side === 0) return wrap180(L[1] - L[0]) / (2 * h);
      const d1 = wrap180(L[1] - L[0]), d2 = wrap180(L[2] - L[0]);
      return side * (4 * d1 - d2) / (2 * h);
    };
    const Es = xs.map((x) => C.vector(S, "E", x));
    const out = { surya: rate(Es.map((E) => scl(E, -1))), candra: rate(xs.map((x) => C.vector(S, "M", x))) };
    for (const [k, b] of Object.entries(SERIES_BODY)) out[k] = rate(xs.map((x, i) => sub(C.vector(S, b, x), Es[i])));
    out.rahu = out.ketu = S.angles.N_M.n;
    return out;
  }
  /** Tropical (apparent, true ecliptic & equinox of date) longitudes, as before: { jdTT, deltaTSeconds, surya…ketu,
   *  _lat, _dist }; null outside the span. opts: { timeScale, ayanamsha: 'citra-paksha' only } (no ayanāṃśa is applied
   *  here; another name is refused all the same). */
  const tropicalGrahas = guarded(function (jd, opts) {
    rejectNamedAyanamsha(opts);
    const SD = getSD(); if (!SD) return null;
    const jdTT = ttOf(jd, opts, "tropicalGrahas"); if (jdTT === null) return null;
    const g = SD.grahaOfDate(jdTT);
    const out = { jdTT, deltaTSeconds: (jdTT - jd) * 86400, _lat: {}, _dist: {}, source: "own" };
    for (const k of ORDER) { const e = ENGINE[k]; out[k] = n360(g[e]); out._lat[k] = g._lat[e]; if (g._dist[e] !== undefined) out._dist[k] = g._dist[e]; }
    return out;
  });
  /** The nine grahas, sidereal (Citrā-pakṣa true): an Array of rows { key, sa, en, longitude, latitude, tropical,
   *  distanceAU, speed, retrograde, source:'own' } in the order surya, candra, mangala, budha, guru, shukra, shani,
   *  rahu, ketu. For the existing callers the array also carries keyed sidereal longitudes (rows.surya …, rows._lat,
   *  rows._dist) and jd, jdTT, ayanamshaDeg (true), ayanamshaMeanDeg, tier, source. null outside the span.
   *  opts: { timeScale: 'TT' } (jd is TT), { speed: false } (skip the speeds), { ayanamsha: 'citra-paksha' }; any other
   *  named ayanāṃśa (including a string second argument) throws. */
  const grahas = guarded(function (jd, opts) {
    rejectNamedAyanamsha(opts);
    const o = optsOf(opts), SD = getSD(); if (!SD) return null;
    const jdTT = ttOf(jd, o, "grahas"); if (jdTT === null) return null;
    const g = SD.grahaOfDate(jdTT), a = ayanParts(jdTT);
    const sp = o.speed === false ? null : speedsTT(jdTT);
    const rows = [];
    rows._lat = {}; rows._dist = {};
    for (const k of ORDER) {
      const e = ENGINE[k];
      const row = {
        key: k, sa: NAMES[k][0], en: NAMES[k][1],
        longitude: n360(g._lonMean[e] - a.mean),
        latitude: g._lat[e], tropical: g[e],
        distanceAU: g._dist[e] !== undefined ? g._dist[e] : null,
        speed: sp ? sp[k] : null, retrograde: sp ? sp[k] < 0 : null,
        source: "own",
      };
      rows.push(row); rows[k] = row.longitude; rows._lat[k] = row.latitude; if (row.distanceAU !== null) rows._dist[k] = row.distanceAU;
    }
    rows.jd = jd; rows.jdTT = jdTT; rows.deltaTSeconds = o.timeScale === "TT" ? null : (jdTT - jd) * 86400;
    rows.ayanamshaDeg = a.true; rows.ayanamshaMeanDeg = a.mean; rows.frame = "citra-paksha"; rows.tier = "drik"; rows.source = "own";
    return rows;
  });

  /** The Sun only (the E vector and velocity): { jd, jdTT, sunTrop, sunSid, sunLat, sunDistAU, ra, dec, ayanamshaDeg,
   *  ayanamshaMeanDeg, source }. sunSid/sunLat/sunTrop are bit-identical to grahas(jd)'s Sun row. null outside.
   *  opts: { timeScale, ayanamsha: 'citra-paksha' only }. */
  const sun = guarded(function (jd, opts) {
    rejectNamedAyanamsha(opts); const o = optsOf(opts);
    const SD = getSD(); if (!SD) return null;
    const jdTT = ttOf(jd, o, "sun"); if (jdTT === null) return null;
    if (!seriesFrameOk(SD)) { const g = grahas(jd, Object.assign({}, o, { speed: false })); return g && { jd, jdTT, sunTrop: g[0].tropical, sunSid: g[0].longitude, sunLat: g[0].latitude, sunDistAU: g[0].distanceAU, source: "own" }; }
    const r = reduceSunMoon(jdTT, false), a = ayanParts(jdTT);
    const lm = lonMeanOf(r.sun.u, r.pA), lat = latOf(r.sun.u), trop = n360(lm + r.dpsi);
    const eps = trueObliquityRad(r.T), rd = raDecOfLonLat(trop, lat, eps);
    return { jd, jdTT, sunTrop: trop, sunSid: n360(lm - a.mean), sunLat: lat, sunDistAU: r.sun.dist, ra: rd.ra, dec: rd.dec,
      ayanamshaDeg: a.true, ayanamshaMeanDeg: a.mean, source: "own" };
  });
  /** Sun and Moon (pañcāṅga limbs): { jd, jdTT, sunTrop, moonTrop, sunSid, moonSid, sunLat, moonLat, sunDistAU,
   *  moonDistAU, elongation (Moon − Sun, 0–360), sunRa, sunDec, moonRa, moonDec, ayanamshaDeg, source }. The sidereal,
   *  tropical and latitude values are bit-identical to grahas(jd)'s Sun and Moon rows. null outside the span.
   *  opts: { timeScale, ayanamsha: 'citra-paksha' only }. */
  const sunMoon = guarded(function (jd, opts) {
    rejectNamedAyanamsha(opts); const o = optsOf(opts);
    const SD = getSD(); if (!SD) return null;
    const jdTT = ttOf(jd, o, "sunMoon"); if (jdTT === null) return null;
    if (!seriesFrameOk(SD)) { const g = grahas(jd, Object.assign({}, o, { speed: false })); return g && { jd, jdTT, sunTrop: g[0].tropical, moonTrop: g[1].tropical, sunSid: g[0].longitude, moonSid: g[1].longitude, sunLat: g[0].latitude, moonLat: g[1].latitude, sunDistAU: g[0].distanceAU, moonDistAU: g[1].distanceAU, elongation: n360(g[1].longitude - g[0].longitude), source: "own" }; }
    const r = reduceSunMoon(jdTT, true), a = ayanParts(jdTT);
    const sl = lonMeanOf(r.sun.u, r.pA), ml = lonMeanOf(r.moon.u, r.pA);
    const sLat = latOf(r.sun.u), mLat = latOf(r.moon.u), sTrop = n360(sl + r.dpsi), mTrop = n360(ml + r.dpsi);
    const eps = trueObliquityRad(r.T), sr = raDecOfLonLat(sTrop, sLat, eps), mr = raDecOfLonLat(mTrop, mLat, eps);
    return { jd, jdTT, sunTrop: sTrop, moonTrop: mTrop, sunSid: n360(sl - a.mean), moonSid: n360(ml - a.mean), sunLat: sLat, moonLat: mLat,
      sunDistAU: r.sun.dist, moonDistAU: r.moon.dist, elongation: n360(ml - sl),
      sunRa: sr.ra, sunDec: sr.dec, moonRa: mr.ra, moonDec: mr.dec, ayanamshaDeg: a.true, ayanamshaMeanDeg: a.mean, source: "own" };
  });

  // ── the kernel the eclipse search (drik-grahana.js) is built on: raw series vectors (guarded), the frame angles, and
  //    the same reduction as sun()/sunMoon() applied to any vector source (the series or its interpolant) ──────────────
  /** Raw series vectors at jdTT: { E (heliocentric Earth), M (geocentric Moon) }, AU, series frame. null outside.
   *  No options. */
  const rawTT = guarded(function (jdTT) {
    requireFinite(jdTT, "eclipseKernel.rawTT", "the Julian day (TT)");
    const SD = getSD(); if (!SD || !seriesFrameOk(SD)) return null;
    need(jdTT);
    const vec = seriesVec(), t = jdTT - J2000;
    return { jdTT, E: vec("E", t), M: vec("M", t) };
  });
  /** Frame angles at jdTT: p_A and Δψ (deg) and the true obliquity (rad). */
  function frameTT(jdTT) {
    const EO = getSD().EO, T = (jdTT - J2000) / 36525;
    return { pA: EO.generalPrecessionArcsec(T) / 3600, dpsi: EO.nutation(T).dpsi / 3600, eps: trueObliquityRad(T) };
  }
  /** Apparent Sun and Moon as unit vectors in the true equator and equinox of date, with distances (AU), from a vector
   *  source vec(body, t) and frame angles fr ({ pA, dpsi, eps }). Not a display value. */
  function apparentEquatorialWith(vec, jdTT, fr) {
    const r = reduceSunMoonWith(vec, jdTT, true);
    return { jdTT, sun: toTrueEquator(r.sun.u, fr.pA, fr.dpsi, fr.eps), sunDistAU: r.sun.dist,
      moon: toTrueEquator(r.moon.u, fr.pA, fr.dpsi, fr.eps), moonDistAU: r.moon.dist };
  }
  /** The same straight from the series at jdTT (null outside the span). No options. */
  const sunMoonVectorsTT = guarded(function (jdTT) {
    requireFinite(jdTT, "eclipseKernel.sunMoonVectorsTT", "the Julian day (TT)");
    const SD = getSD(); if (!SD || !seriesFrameOk(SD)) return null;
    need(jdTT); need(jdTT - VELOCITY_STEP); need(jdTT + VELOCITY_STEP);
    return apparentEquatorialWith(seriesVec(), jdTT, frameTT(jdTT));
  });
  const ECLIPSE_KERNEL = Object.freeze({ rawTT, frameTT, apparentEquatorialWith, sunMoonVectorsTT, VELOCITY_STEP,
    toTrueEquator, gastDegTT: (jdUT, jdTT) => getSD().EO.gastDeg(jdUT, (jdTT - J2000) / 36525) });

  // ── Earth rotation and the horizon ──────────────────────────────────────────────────────────────────────────────
  /** Apparent sidereal time at Greenwich (degrees), IAU 2006 (ERA + GMST polynomial + equation of the equinoxes) from
   *  the embedded EO, UT1 = UTC assumed (|UT1 − UTC| < 0.9 s). null outside the span. No options (no ayanāṃśa
   *  enters); a named ayanāṃśa in an extra argument is refused. */
  const gast = guarded(function (jd, extra) {
    rejectNamedAyanamsha(extra);
    const SD = getSD(); if (!SD) return null;
    const jdTT = ttOf(jd, undefined, "gast"); if (jdTT === null) return null;
    return SD.EO.gastDeg(jd, (jdTT - J2000) / 36525);
  });
  function checkSite(lat, lonEast, entry) {
    requireFinite(lat, entry, "the latitude"); requireFinite(lonEast, entry, "the east longitude");
    if (Math.abs(lat) >= 90) throw new RangeError("SiddhantaTier: latitude must be a finite number strictly between −90 and 90 degrees");
    if (Math.abs(lonEast) > 360) throw new RangeError("SiddhantaTier: east longitude must be a finite number of degrees");
  }
  /** Lagna and madhya-lagna (port of chart.cjs:83-91 ascMc): tropical (true equinox of date) and sidereal (− the true
   *  Citrā-pakṣa ayanāṃśa). { asc, mc (sidereal), ascTropical, mcTropical, tropical, sidereal, mcSidereal, ramcDeg,
   *  ayanamshaDeg, source }. null outside the span. opts: { ayanamsha: 'citra-paksha' only }. */
  const lagna = guarded(function (jd, lat, lonEast, opts) {
    requireFinite(jd, "lagna", "the Julian day");
    checkSite(lat, lonEast, "lagna");
    rejectNamedAyanamsha(opts);
    const SD = getSD(); if (!SD) return null;
    const jdTT = ttOf(jd, undefined, "lagna"); if (jdTT === null) return null;
    const EO = SD.EO, T = (jdTT - J2000) / 36525;
    const { deps } = EO.nutation(T);
    const eps = EO.meanObliquityRad(T) + deps * EO.AS2R;
    const ramcDeg = n360(EO.gastDeg(jd, T) + lonEast), ramc = ramcDeg * DEG, phi = lat * DEG;
    const ascT = n360(Math.atan2(Math.cos(ramc), -(Math.sin(ramc) * Math.cos(eps) + Math.tan(phi) * Math.sin(eps))) / DEG);
    const mcT = n360(Math.atan2(Math.sin(ramc), Math.cos(ramc) * Math.cos(eps)) / DEG);
    const a = ayanParts(jdTT);
    const asc = n360(ascT - a.true), mc = n360(mcT - a.true);
    return { jd, jdTT, asc, mc, ascTropical: ascT, mcTropical: mcT, tropical: ascT, sidereal: asc, mcSidereal: mc, ramcDeg,
      ayanamshaDeg: a.true, method: "apparent sidereal time (IAU 2006 GAST), true obliquity; chart.cjs ascMc", source: "own" };
  });

  const SUN_HORIZON_DEG = -50 / 60, MOON_HORIZON_DEG = 7 / 60;
  const SIDEREAL_RATE = 360.98564736629;                 // deg of Earth rotation per UT day
  /** Geocentric RA/Dec of the body at a UT instant; throws OUT outside the span (caught by the public entry). */
  function bodyRaDec(kind, jd) {
    if (ttOf(jd) === null) throw OUT;
    if (kind === "sun") { const s = sun(jd); return { ra: s.ra, dec: s.dec, gast: gast(jd) }; }
    const m = sunMoon(jd); return { ra: m.moonRa, dec: m.moonDec, gast: gast(jd) };
  }
  function transitNear(kind, guess, lonEast) {
    const rate = kind === "sun" ? 360.0 : 347.8;           // hour-angle rate, deg/day (Sun ≈ 360, Moon ≈ 347.8)
    let t = guess;
    for (let i = 0; i < 12; i++) {
      const s = bodyRaDec(kind, t), H = wrap180(s.gast + lonEast - s.ra);
      const dt = -H / rate; t += dt;
      if (Math.abs(dt) < 1e-9) break;
    }
    return t;
  }
  /** The lower transit (hour angle 180°) nearest the guess. */
  function lowerTransitNear(kind, guess, lonEast) {
    const rate = kind === "sun" ? 360.0 : 347.8;
    let t = guess;
    for (let i = 0; i < 12; i++) {
      const s = bodyRaDec(kind, t), H = wrap180(s.gast + lonEast - s.ra - 180);
      const dt = -H / rate; t += dt;
      if (Math.abs(dt) < 1e-9) break;
    }
    return t;
  }
  /** The hour-angle iteration below takes the declination of one instant; for a grazing Moon at high latitude (its
   *  declination moves up to ≈ 2.5° in half a day) it can call 'polar' an event that happens. Such a verdict is checked
   *  by the altitudes at the upper transit tTr and the neighbouring lower transit on the event's side: when they straddle
   *  h0 the crossing is bracketed between them (bisection with secant steps, to 1e-9 d); otherwise the verdict stands. */
  function grazingEvent(kind, tTr, sign, lat, lonEast, h0, polar) {
    const phi = lat * DEG;
    const f = (t) => { const s = bodyRaDec(kind, t), d = s.dec * DEG, H = (s.gast + lonEast - s.ra) * DEG;
      return Math.asin(Math.max(-1, Math.min(1, Math.sin(phi) * Math.sin(d) + Math.cos(phi) * Math.cos(d) * Math.cos(H)))) / DEG - h0; };
    const tL = lowerTransitNear(kind, tTr + sign * (kind === "sun" ? 0.5 : 0.5175), lonEast);
    let a = tTr, b = tL, fa = f(a), fb = f(b);
    if (!(fa > 0 && fb < 0)) return { polar };
    for (let k = 0; k < 120 && Math.abs(b - a) > 1e-9; k++) {
      let m = b - fb * (b - a) / (fb - fa);
      if (!(m > Math.min(a, b) && m < Math.max(a, b)) || k % 3 === 2) m = (a + b) / 2;
      const fm = f(m);
      if (fm > 0) { a = m; fa = fm; } else { b = m; fb = fm; }
    }
    return { jd: (a + b) / 2 };
  }
  /** Rise (sign −1) or set (+1) belonging to the upper transit tTr: iterate on the hour angle until the altitude equals
   *  h0 exactly (spherical formula). Returns { jd } or { polar: 'up' | 'down' }. */
  function horizonEvent(kind, tTr, sign, lat, lonEast, h0) {
    const rate = kind === "sun" ? 360.0 : 347.8, phi = lat * DEG, sh0 = Math.sin(h0 * DEG);
    const cosH0 = (s) => (sh0 - Math.sin(phi) * Math.sin(s.dec * DEG)) / (Math.cos(phi) * Math.cos(s.dec * DEG));
    let s = bodyRaDec(kind, tTr), c = cosH0(s);
    if (c < -1) return grazingEvent(kind, tTr, sign, lat, lonEast, h0, "up");
    if (c > 1) return grazingEvent(kind, tTr, sign, lat, lonEast, h0, "down");
    let t = tTr + sign * Math.acos(c) / DEG / rate;
    for (let i = 0; i < 16; i++) {
      s = bodyRaDec(kind, t); c = cosH0(s);
      if (c < -1) return grazingEvent(kind, tTr, sign, lat, lonEast, h0, "up");
      if (c > 1) return grazingEvent(kind, tTr, sign, lat, lonEast, h0, "down");
      const target = sign * Math.acos(c) / DEG, H = wrap180(s.gast + lonEast - s.ra);
      const dt = wrap180(target - H) / rate; t += dt;
      if (Math.abs(dt) < 1e-9) break;
    }
    return { jd: t };
  }
  /** Rise, set and upper transit of the Sun or the Moon inside the civil day [dayJdUT, dayJdUT + 1) (dayJdUT = the UT
   *  Julian day of the local midnight that starts the day). Sun: upper limb with 34′ refraction (centre −50′); Moon:
   *  centre on a net +7′ geocentric horizon (DK-5). { kind, riseJd, setJd, transitJd, polar, horizonDeg, rule, source }
   *  (riseJd/setJd null when the body does not rise/set inside the day). null when any instant needed lies outside the
   *  span. opts: { events: true } adds `events` (below); { ayanamsha: 'citra-paksha' only } (no ayanāṃśa enters a rise or
   *  set; another name is refused).
   *  TWO RISES OR TWO SETS IN ONE DAY: at high latitude the Moon (and, near the polar circles, the Sun) can rise twice or
   *  set twice inside one civil day (drik-bharatiya.test.js counts such days at Tromsø). riseJd and setJd keep their
   *  meaning — the event of the day's own transit when it falls inside the day, else the one of the next (rise) or
   *  previous (set) transit — so on such a day they give one of the two. With opts.events, `events` lists every rise and
   *  set inside the day, in time order: [{ kind: 'rise' | 'set', jd }], each the event of one upper transit found as
   *  riseJd/setJd are; a day with two rises holds two { kind: 'rise' } entries. It costs up to one more transit and one
   *  more horizon crossing, so it is computed only when asked. events is null (riseJd, setJd, transitJd as computed) when
   *  a neighbouring transit it needs lies outside the span. */
  const riseSet = guarded(function (kind, dayJdUT, lat, lonEast, opts) {
    if (kind !== "sun" && kind !== "moon") throw new RangeError("SiddhantaTier.riseSet: kind must be 'sun' or 'moon'");
    requireFinite(dayJdUT, "riseSet", "the day's Julian day (UT)");
    checkSite(lat, lonEast, "riseSet");
    rejectNamedAyanamsha(opts);
    const wantEvents = optsOf(opts).events === true;
    if (!getSD()) return null;
    const h0 = kind === "sun" ? SUN_HORIZON_DEG : MOON_HORIZON_DEG;
    const cycle = kind === "sun" ? 1.0 : 1.035;
    const d0 = dayJdUT, d1 = dayJdUT + 1;
    let tr = transitNear(kind, d0 + 0.5, lonEast);                     // from the civil noon of the day
    if (tr < d0) tr = transitNear(kind, tr + cycle, lonEast); else if (tr >= d1) tr = transitNear(kind, tr - cycle, lonEast);
    const transitJd = (tr >= d0 && tr < d1) ? tr : null;
    let polar = null;
    // the transits k = −1, 0, +1 (k · cycle from the day's own) and their events, each computed once
    const transits = new Map([[0, tr]]), evs = new Map();
    const transitK = (k) => { if (!transits.has(k)) transits.set(k, transitNear(kind, tr + k * cycle, lonEast)); return transits.get(k); };
    const eventK = (k, sign) => { const key = `${k}:${sign}`; if (!evs.has(key)) evs.set(key, horizonEvent(kind, transitK(k), sign, lat, lonEast, h0)); return evs.get(key); };
    const pick = (sign) => {
      for (const k of [0, sign < 0 ? 1 : -1, sign < 0 ? -1 : 1]) {
        const ev = eventK(k, sign);
        if (ev.polar) { if (k === 0) polar = ev.polar; continue; }
        if (ev.jd >= d0 && ev.jd < d1) return ev.jd;
      }
      return null;
    };
    const riseJd = pick(-1), setJd = pick(+1);
    // every event inside the day: a rise lies within half a turn before its transit, a set within half a turn after it
    // (the hour angle at the body's rate, and grazingEvent brackets no wider), so only those transits are asked whose
    // side can reach the day (0.05 d covers the error of tr + k · cycle as an estimate of the transit)
    let events = wantEvents ? [] : undefined;
    if (wantEvents) try {
      for (const k of [-1, 0, 1]) for (const sign of [-1, 1]) {
        const est = tr + k * cycle, half = cycle / 2 + 0.05;
        if (sign < 0 ? (est + 0.05 < d0 || est - half >= d1) : (est - 0.05 >= d1 || est + half < d0)) continue;
        const ev = eventK(k, sign);
        if (ev.polar || !(ev.jd >= d0 && ev.jd < d1)) continue;
        if (!events.some((e) => e.kind === (sign < 0 ? "rise" : "set") && Math.abs(e.jd - ev.jd) < 1e-6)) events.push({ kind: sign < 0 ? "rise" : "set", jd: ev.jd });
      }
      events.sort((a, b) => a.jd - b.jd);
    } catch (e) { if (e === OUT) events = null; else throw e; }
    const out = { kind, dayJdUT: d0, riseJd, setJd, transitJd, polar: riseJd === null && setJd === null ? polar : null, horizonDeg: h0,
      noonJd: kind === "sun" ? transitJd : undefined,
      rule: kind === "sun" ? "the Sun's upper limb on the horizon with 34′ refraction (centre at −50′) [convention]; IAU 2006 GAST"
        : "the Moon's centre on a net +7′ geocentric horizon (parallax − refraction − semi-diameter) [convention, DK-5; KH-13]; IAU 2006 GAST",
      source: "own" };
    if (wantEvents) out.events = events;
    return out;
  });
  /** riseSet('sun', …) as { riseJd, setJd, noonJd, polar, events (with { events: true }), rule, source }. opts as
   *  riseSet's. */
  const withEvents = (o, r) => { if (r.events !== undefined) o.events = r.events; return o; };
  const sunEvents = (jdMidnightUT, lat, lonEast, opts) => { const r = riseSet("sun", jdMidnightUT, lat, lonEast, opts); return r && withEvents({ riseJd: r.riseJd, setJd: r.setJd, noonJd: r.transitJd, polar: r.polar, rule: r.rule, source: "own" }, r); };
  /** riseSet('moon', …) as { riseJd, setJd, transitJd, horizonDeg, events (with { events: true }), rule, source }. opts
   *  as riseSet's. */
  const moonEvents = (jdMidnightUT, lat, lonEast, opts) => { const r = riseSet("moon", jdMidnightUT, lat, lonEast, opts); return r && withEvents({ riseJd: r.riseJd, setJd: r.setJd, transitJd: r.transitJd, horizonDeg: r.horizonDeg, rule: r.rule, source: "own" }, r); };

  // ── sky events: syzygies, saṅkrāntis and the amānta month (EDGE RULE: null when any instant is outside) ─────────────
  const SYNODIC_RATE = 12.190749, SOLAR_RATE = 0.985647;
  function elongAt(jd) { const m = sunMoon(jd); if (!m) throw OUT; return m; }
  function sunSidAt(jd) { const s = sun(jd); if (!s) throw OUT; return s.sunSid; }
  /** Newton on f(t) = wrap180(F(t) − target) with a nominal rate, then secant; to 1e-8 d. */
  function solveAngle(F, target, guess, rate) {
    let t = guess, f = wrap180(F(t) - target), tPrev = null, fPrev = null;
    for (let i = 0; i < 30; i++) {
      let r = rate;
      if (tPrev !== null && Math.abs(t - tPrev) > 1e-12 && Math.abs(f - fPrev) > 1e-15) r = (f - fPrev) / (t - tPrev);
      if (!(r > 0)) r = rate;
      const dt = -f / r; tPrev = t; fPrev = f; t += dt; f = wrap180(F(t) - target);
      if (Math.abs(dt) < 1e-8) break;
    }
    return t;
  }
  /** The syzygy (elongation = target, 0 new moon / 180 full moon) at or before jd (dir −1) or after it (dir +1). No
   *  options (the elongation needs no ayanāṃśa): a named ayanāṃśa in an extra argument is refused. */
  const syzygy = guarded(function (jd, target, dir, extra) {
    requireFinite(jd, "syzygy", "the Julian day");
    rejectNamedAyanamsha(extra);
    if (target !== 0 && target !== 180) throw new RangeError("SiddhantaTier.syzygy: target must be 0 or 180");
    if (dir !== -1 && dir !== 1) throw new RangeError("SiddhantaTier.syzygy: dir must be −1 or +1");
    const e0 = elongAt(jd).elongation;
    const delta = dir > 0 ? n360(target - e0) : -n360(e0 - target);
    let t = solveAngle((x) => elongAt(x).elongation, target, jd + delta / SYNODIC_RATE, SYNODIC_RATE);
    if (dir > 0 && t <= jd) t = solveAngle((x) => elongAt(x).elongation, target, t + 29.53, SYNODIC_RATE);
    if (dir < 0 && t > jd) t = solveAngle((x) => elongAt(x).elongation, target, t - 29.53, SYNODIC_RATE);
    return t;
  });
  /** Saṅkrāntis (the sidereal Sun entering a rāśi) in (jd0, jd1]: [{ jd, index (0 = Meṣa) }]. No options: the rāśis are
   *  Citrā-pakṣa's (true); a named ayanāṃśa in an extra argument is refused. */
  const sankrantisBetween = guarded(function (jd0, jd1, extra) {
    requireFinite(jd0, "sankrantisBetween", "the first Julian day"); requireFinite(jd1, "sankrantisBetween", "the last Julian day");
    rejectNamedAyanamsha(extra);
    const out = [];
    let t = jd0, s = sunSidAt(t);
    for (let guard = 0; guard < 2000 && t < jd1; guard++) {
      const idx = (Math.floor(s / 30) + 1) % 12, target = idx * 30;
      const guess = t + n360(target - s) / SOLAR_RATE;
      if (guess - 2 > jd1) break;
      const tc = solveAngle(sunSidAt, target, guess, SOLAR_RATE);
      if (tc > jd1) break;
      if (tc > jd0) out.push({ jd: tc, index: idx });
      t = tc + 1e-6; s = sunSidAt(t);
    }
    return out;
  });
  /** The amānta lunar month containing jd: { start, end, fullMoon, sankrantis, nextSankranti, name, adhika, kshaya,
   *  kshayaDropped, source:'own', rule } — named by Panchanga.nameMonth (one rule for both tiers) when panchanga.js is
   *  loaded. null when the month or any instant it needs (the next saṅkrānti of an adhika month) is outside the span.
   *  No options: the month is named by Citrā-pakṣa (true) saṅkrāntis; a named ayanāṃśa in an extra argument is refused
   *  (it is never silently ignored). */
  const lunarMonth = guarded(function (jd, extra) {
    requireFinite(jd, "lunarMonth", "the Julian day");
    rejectNamedAyanamsha(extra);
    const start = syzygy(jd, 0, -1); if (start === null) throw OUT;
    const end = syzygy(start + 1, 0, +1); if (end === null) throw OUT;
    const fullMoon = syzygy(start + 1, 180, +1); if (fullMoon === null) throw OUT;
    const sankrantis = sankrantisBetween(start, end); if (sankrantis === null) throw OUT;
    let nextSankranti = null;
    if (sankrantis.length === 0) { const nx = sankrantisBetween(end, end + 33); if (nx === null || !nx.length) throw OUT; nextSankranti = nx[0]; }
    const out = { start, end, fullMoon, sankrantis, nextSankranti, source: "own",
      rule: "amānta: new moon to new moon; saṅkrānti in the month names it (Meṣa → Caitra …); none → adhika, named after the next [standard]" };
    const P = getPanchanga();
    if (P && typeof P.nameMonth === "function") Object.assign(out, P.nameMonth(sankrantis.map((x) => x.index), nextSankranti ? nextSankranti.index : undefined));
    return out;
  });

  // ── window table for month-calendar views (4-point Lagrange on unwrapped longitudes) ────────────────────────────────
  /** Sun and Moon on a grid [jd0, jd1] every stepDays (default 0.25 d); at(jd) interpolates { sunSid, moonSid, sunTrop,
   *  moonTrop, elongation } (measured ≤ 0.02″ for the Moon at 0.25 d). null if any node is outside the span; at(jd)
   *  returns null outside [jd0, jd1]. No options (sidereal values are Citrā-pakṣa true): a named ayanāṃśa in an extra
   *  argument is refused. */
  const table = guarded(function (jd0, jd1, stepDays, extra) {
    requireFinite(jd0, "table", "the first Julian day"); requireFinite(jd1, "table", "the last Julian day");
    rejectNamedAyanamsha(extra);
    const h = stepDays === undefined ? 0.25 : stepDays;
    if (!(jd1 > jd0) || !(h > 0)) throw new RangeError("SiddhantaTier.table: needs jd1 > jd0 and a positive step");
    const n = Math.max(4, Math.ceil((jd1 - jd0) / h) + 1), cols = { sunSid: [], moonSid: [], sunTrop: [], moonTrop: [] };
    for (let i = 0; i < n; i++) { const m = sunMoon(jd0 + i * h); if (!m) throw OUT; for (const k in cols) cols[k].push(m[k]); }
    for (const k in cols) { const y = cols[k]; for (let i = 1; i < y.length; i++) { let d = y[i] - y[i - 1]; d -= 360 * Math.round(d / 360); y[i] = y[i - 1] + d; } }
    const lag = (y, x) => { const i = Math.min(Math.max(Math.floor(x) - 1, 0), y.length - 4); let s = 0;
      for (let j = 0; j < 4; j++) { let w = 1; for (let k = 0; k < 4; k++) if (k !== j) w *= (x - (i + k)) / (j - k); s += w * y[i + j]; } return s; };
    const last = jd0 + (n - 1) * h;
    return { jd0, jd1: last, step: h, source: "own",
      at(jd) { if (!(jd >= jd0 && jd <= last)) return null; const x = (jd - jd0) / h, o = {};
        for (const k in cols) o[k] = n360(lag(cols[k], x)); o.elongation = n360(o.moonSid - o.sunSid); return o; } };
  });

  // ── eclipses: drik-grahana.js on this tier's own Sun and Moon ─────────────────────────────────────────────────────
  function getGrahana() {
    if (root.DrikGrahana) return root.DrikGrahana;
    if (typeof require === "function") { try { return require("./drik-grahana.js"); } catch (e) { /* not present */ } }
    return null;
  }
  /** Lunar and solar eclipses whose maximum falls in [fromJdUT, toJdUT], from this tier's series (DK-3). With a site
   *  { latitude, longitude } each row also carries its local circumstances. null when any part is outside the span;
   *  TypeError when a Julian day is not a finite number. opts: drik-grahana.js's ({ kinds }; referee tests only:
   *  conventions, vectorSource) and { ayanamsha: 'citra-paksha' only }. */
  function eclipses(fromJdUT, toJdUT, site, opts) {
    requireFinite(fromJdUT, "eclipses", "the first Julian day"); requireFinite(toJdUT, "eclipses", "the last Julian day");
    rejectNamedAyanamsha(opts);
    const G = getGrahana();
    if (!G) throw new Error("SiddhantaTier.eclipses: drik-grahana.js is not loaded");
    return G.eclipses(fromJdUT, toJdUT, site, opts);
  }

  // ── labels (the pages render these; numbers measured in drik-bharatiya.test.js and the design's harnesses) ─────────
  const LABEL = Object.freeze({
    id: "drik",
    name: "Modern Bhāratīya (dṛk)",
    nameSa: "आधुनिक भारतीय (दृक्)",
    engine: "Our dṛk-siddhānta series v2.4.2, arranged in the Sūrya-Siddhānta's order (madhyama, manda, śīghra): 12,901 periodic terms evaluated with Mādhava's sine. Its coefficients were fitted to our N-body (DOP853: Newton + EIH 1PN + Earth J2 + lunar figure + LLR tide), which is restarted from NASA-JPL DE440s states every 720 days.",
    reduction: "Light-time, the Sun's deflection of planetary light and annual aberration are ours (the Moon: its own light-time; the Sun: aberration). Precession is IAU 2006 and nutation IAU 2000B, in our implementation of the IAU models.",
    time: "ΔT: annual table 1800–2027 (Stephenson–Morrison–Hohenkerk/AA to 1954, IERS after; the 2027 value is an IERS prediction), Espenak–Meeus prediction after that (196 s in 2100, 322 s in 2150). Civil times after 2027 carry that prediction's uncertainty.",
    ayanamsha: "Citrā-pakṣa (Lahiri), the Calendar Reform Committee's convention [standard]. Realised with the IAE value 23°15′00.658″ for 1956-03-21 (true equinox), carried by IAU 2006 general precession, as Swiss SE_SIDM_LAHIRI (+0.138″). Applied true (mean + nutation); the value shown is the value applied.",
    sunrise: "The Sun's upper limb on the horizon with 34′ refraction (centre at −50′) [convention]; apparent sidereal time IAU 2006.",
    moonrise: "The Moon's centre at a net +7′ horizon [convention, as before].",
    lagna: "Lagna and madhya-lagna from apparent sidereal time (IAU 2006) and the true obliquity, minus the same Citrā-pakṣa ayanāṃśa; UT1 = UTC assumed.",
    rahu: "Mean node: the series' fitted node line; Ketu = Rāhu + 180°.",
    eclipses: "Eclipses searched on this tier's own Sun and Moon (drik-grahana.js): lunar with Danjon's shadow (Earth's radius + 1/85, oblateness 1/594), solar by the shadow cone of the Sun and Moon on the IERS 2010 ellipsoid; k = 0.2725076 (0.272281 for the umbral contacts).",
    range: "Ours 1850.0–2150.0. Agreement with NASA-JPL DE440s: λ ≤ 0.9″ (dense check, 1850–2150). This is not independent of JPL, because our N-body is restarted from DE440s states every 720 days. Outside 1850–2150: refused.",
    refusal: "आधुनिक भारतीय (दृक्) — our derivations are valid 1850.0–2150.0 only; outside that span this tier refuses (no foreign substitute).",
  });
  const PROVENANCE = Object.freeze({
    chain: Object.freeze([
      "law: DOP853, Newton + EIH 1PN + Earth J2 + lunar figure + LLR tide (bharat-sovereign-engine harnesses/siddhanta-reference.cjs)",
      "reference: 154 NASA-JPL DE440s states 720 d apart (jplephem), each integrated ±360 d",
      "fit: 146,025 daily samples 1800.12–2199.91 (series v2.4.2, built 2026-09-22)",
      "evaluation: drik-siddhanta-core (siddhanta-drik.js)",
      "reduction: light-time, solar deflection, aberration (drik-siddhanta-core apparent())",
      "Earth orientation: IAU 2006 / 2000B (embedded earth-orientation)",
      "ayanāṃśa: Citrā-pakṣa (chart.cjs:53-75), true",
      "sunrise, lagna: IAU 2006 GAST (chart.cjs:83-91 for the lagna)",
      "eclipses: drik-grahana.js on this tier's Sun and Moon",
    ]),
    externalInputs: Object.freeze(["DE440s initial states (through the fit)", "DE440 GM values, J2, lunar figure constants, the LLR tidal rate, c, the AU",
      "the IAU 2006/2000B models", "the ΔT data", "the IAE ayanāṃśa constant and Swiss's +0.138″", "for eclipses: the IERS 2010 ellipsoid, k = 0.2725076/0.272281, the solar semi-diameter 959.63″ at 1 AU"]),
    mayNotClaim: Object.freeze(["independent of JPL", "predictive outside 1850–2150", "more accurate than VSOP87B + ELP for positions",
      "Earth orientation from first principles", "ΔT as ours", "arcsecond accuracy for civil times after 2027", "a true node", "2PN in the force model",
      "Mādhava's sine throughout"]),
    span: SPAN_YEARS,
    accuracyMeasured: "λ ≤ 0.9″ vs DE440s (geometric: 0.843″ max every 100 d in drik-bharatiya.test.js, the same every 20 d in the design's check; 0.81″ at 180 apparent fixture epochs). The design's Swiss/DE431 figures (λ ≤ 0.79″, β ≤ 0.50″, 1000 epochs) are not reproducible in this repository: the Swiss data are not committed (DK-4)",
    eclipsesMeasured: "1900–2100: 457 lunar and 452 solar eclipses, one-to-one with Astronomy Engine's searches, none missing or extra; peaks within 9 s (its Moon is ≈ 6″ from DE440); fed Astronomy Engine's own Sun, Moon and constants, this geometry reproduces its search within 1 s; on VSOP87B + ELP/MPP02 within 0.8 s (2000–2030) — drik-bharatiya.test.js",
  });

  function series() { const SD = getSD(); return SD ? SD.series : null; }
  root.SiddhantaTier = {
    available: () => Boolean(getSD()),
    span: () => SPAN_YEARS.slice(),
    certifiedSpan: () => SPAN_YEARS.slice(),
    spanJdUT, inSpan, inSpanTT, deltaTSeconds, utOfTT,
    // jdTTofUT(jd): the TT Julian day of a UT one (ΔT above); no options; TypeError when jd is not a finite number
    jdTTofUT: (jd) => requireFinite(jd, "jdTTofUT", "the Julian day (UT)") + deltaTSeconds(jd) / 86400,
    ayanamsha, tropicalGrahas, grahas, sun, sunMoon, gast, lagna, riseSet, sunEvents, moonEvents,
    syzygy, sankrantisBetween, lunarMonth, table, eclipses,
    eclipseKernel: ECLIPSE_KERNEL,
    series, bhaganas: () => { const S = series(); return S ? S.bhaganas : null; },
    certification: () => { const S = series(); return S ? (S.certification || null) : null; },
    ORDER, LABEL, PROVENANCE,
    CONSTANTS: Object.freeze({ LAHIRI_T0_JD, LAHIRI_IAE_TRUE_DEG, DPSI_T0_SWISS_DEG, SWISS_REALISATION_ARCSEC, LAHIRI_T0_MEAN_DEG,
      SUN_HORIZON_DEG, MOON_HORIZON_DEG, SPEED_STEP_DAYS }),
    seal: "Modern Bhāratīya (dṛk): the owner's series → Sūrya-Siddhānta order · substrate: bharat-sovereign-engine",
  };
  if (typeof module === "object" && module.exports) module.exports = root.SiddhantaTier;
})(typeof globalThis !== "undefined" ? globalThis : this);
