'use strict';
/*
 * derive-gurutva.cjs — runs the gravitational derivation of the Moon from the Sūrya-Siddhānta's numbers alone
 * (gurutva.js, integrated by radau.js) and writes
 *   corpus/gurutva/candra.json   the inputs, the fitted starting state, the mean elements, the derived rates against the
 *                                text's, the inclination the text's apogee rate implies, and the periodic series;
 *   gurutva-candra.js            the series as a browser/node module: the text's mean Moon plus gravitation's terms.
 * No other source enters. Run: node scripts/derive-gurutva.cjs   (about half a minute)
 */
const fs = require('node:fs');
const path = require('node:path');
const G = require('../gurutva.js');
const root = path.resolve(__dirname, '..');
const round = (x, k = 6) => Math.round(x * 10 ** k) / 10 ** k;

const t0 = Date.now();
const d = G.derive({ years: 74.4, refine: 2 });
const implied = G.impliedInclination();
const secs = (Date.now() - t0) / 1000;

const out = {
  _provenance: {
    what: "The Moon by gravitation (the owner's n-body law, tidal limit, the owner's Gauss–Radau integrator), with every input taken from the Sūrya-Siddhānta. Regenerate with node scripts/derive-gurutva.cjs.",
    inputs: G.INPUTS.source,
    reading: "The text's lunar equation and greatest latitude are read as syzygy values: (sin M) − (sin 2D−M) = the first harmonic of its equation, (sin F) − (sin 2D−F) = 270′.",
    left_out: "The parallactic inequality (needs the Moon-to-Sun distance ratio; the text's kakṣās are equal-speed orbits) and the planets (no masses in the text).",
  },
  epoch: { kaliDay: d.epoch, gregorian: '2026-10-07' },
  inputs: { nMoonRadPerDay: G.INPUTS.nMoon, nSunRadPerDay: G.INPUTS.nSun, eSun: round(G.INPUTS.eSun, 8), sunEquationHarmonicDeg: round(G.INPUTS.sunHarmonicDeg), moonEquationHarmonicDeg: round(G.INPUTS.moonHarmonicDeg), latitudeDeg: G.INPUTS.latitudeDeg },
  fitted: { initialOsculating: { a: d.initial.a, e: d.initial.e, iDeg: d.initial.i * 180 / Math.PI, nodeDeg: d.initial.node * 180 / Math.PI, perigeeDeg: d.initial.peri * 180 / Math.PI, meanLongitudeDeg: d.initial.L * 180 / Math.PI },
    meanEccentricity: round(d.meanEcc), meanInclinationDeg: round(d.meanIncDeg), syzygyEquationDeg: round(d.syzygyEquation), syzygyLatitudeDeg: round(d.syzygyLatitude) },
  rates: { span_years: d.span.years, moonPerYuga: round(d.rates.moonPerYuga, 1), apogeePerYuga: round(d.rates.apogeePerYuga, 1), nodePerYuga: round(d.rates.nodePerYuga, 1),
    text: { moon: 57753336, apogee: G.TEXT_RATES.apogee, node: G.TEXT_RATES.node }, apogeeRatio: round(d.rates.apogeeRatio, 7), nodeRatio: round(d.rates.nodeRatio, 7) },
  impliedByTheTextsApogeeRate: { syzygyLatitudeDeg: round(implied.syzygyLatitudeDeg), meanInclinationDeg: round(implied.meanInclinationDeg), apogeeRatio: round(implied.apogeeRatio, 7), nodeRatio: round(implied.nodeRatio, 7), span: implied.span },
  series: {
    arguments: "D = mean Moon − mean Sun; M = mean Moon − (apogee + 180°); M′ = mean Sun − (Sun's apogee + 180°); F = mean Moon − node; all from the text",
    longitude: d.lon.map((x) => ({ arg: x.arg, name: x.name, sin: round(x.sin), cos: round(x.cos) })),
    latitude: d.lat.map((x) => ({ arg: x.arg, name: x.name, sin: round(x.sin), cos: round(x.cos) })),
  },
  run: { steps: d.span.steps, evaluations: d.span.evaluations },
};
fs.writeFileSync(path.join(root, 'corpus', 'gurutva', 'candra.json'), JSON.stringify(out, null, 1) + '\n');

const js = `/* gurutva-candra.js — GENERATED by scripts/derive-gurutva.cjs from corpus/gurutva/candra.json; do not edit by hand.
 * The text's mean Moon (Sūrya-Siddhānta) with the periodic terms that Newton's law adds when it is given only the text's
 * numbers: the equation of centre and its harmonics, evection, variation, the annual equation, the reduction to the
 * ecliptic, and the latitude terms. The arguments are the text's own mean elements. The Sun stays the text's Sun.
 * placesAt(t) has the shape of Sphuta.sphutaAtDays(t), so Panchanga.withPlaces(GurutvaCandra.placesAt) uses it.
 * Browser: window.GurutvaCandra (needs Sphuta); node: module.exports.
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory(require("./sphuta.js").withSine("table"));
  else root.GurutvaCandra = factory(root.Sphuta.withSine("table"));
})(typeof globalThis !== "undefined" ? globalThis : this, function (S) {
  "use strict";
  const D2R = Math.PI / 180, mod = (a, m) => ((a % m) + m) % m;
  const LON = Object.freeze(${JSON.stringify(out.series.longitude.map((x) => [...x.arg, x.sin, x.cos]))});
  const LAT = Object.freeze(${JSON.stringify(out.series.latitude.map((x) => [...x.arg, x.sin, x.cos]))});
  const RATES = Object.freeze(${JSON.stringify(out.rates)});
  function sum(list, a) { let s = 0; for (const r of list) { const x = (r[0] * a[0] + r[1] * a[1] + r[2] * a[2] + r[3] * a[3]) * D2R; s += r[4] * Math.sin(x) + r[5] * Math.cos(x); } return s; }
  /** Places at t (civil days since the Kali epoch): the text's Sun and node; the Moon by the text's mean and gravitation's terms. */
  function placesAt(t) {
    const base = S.sphutaAtDays(t), m = base.mean;
    const a = [m.moon - m.sun, m.moon - m.moonApogee - 180, m.sun - m.sunApogee - 180, m.moon - m.node];
    const dl = sum(LON, a);
    return { ...base, moon: mod(m.moon + dl, 360), moonLatitude: sum(LAT, a), equations: { ...base.equations, moon: { degrees: dl, model: "gurutva" } }, model: "gurutva" };
  }
  return Object.freeze({ LON, LAT, RATES, placesAt });
});
`;
fs.writeFileSync(path.join(root, 'gurutva-candra.js'), js);
console.log(JSON.stringify({ rates: out.rates, implied: out.impliedByTheTextsApogeeRate, seconds: Math.round(secs) }, null, 1));
